- name: conditions
  hosts: localhost
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print user information
    ansible.builtin.debug:
    msg: "print user: {{USER}}"
