- name: Filters
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "printing {{course | default('ansible')}}"

  - name: upper case
    vars:
      greeting: Good Morning
    ansible.builtin.debug:
      msg: "printing uppercase {{greeting | upper}}"

  - name: lower case
    vars:
      greeting: Good Morning
    ansible.builtin.debug:
      msg: "printing lowercase {{greeting | lower}}"