- name: Filters
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "printing {{course | default('ansible')}}"

  - name: upper case
    vars:
      greeting: Good Morning
    ansible.builtin.debug:
      msg: "printing uppercase {{greeting | upper}}"

  - name: lower case
    vars:
      greeting: Good Morning
    ansible.builtin.debug:
      msg: "printing lowercase {{greeting | lower}}"

  - name: unique values
    vars:
      num: [1,2,4,4,4,5,5,7,8]
    ansible.builtin.debug:
      msg: "printing unique {{num | unique}}"

  - name: min and max
    vars:
      num: [31,6,90,3]
    ansible.builtin.debug:
      msg: "printing min {{num | min}} and max {{num | max}}"
  
  - name: dictionary
    vars:
      mydict:
        course: Ansible
        Trainer: Siva
        Duration: 40hrs
    tasks:
    - name: before convert
      ansible.builtin.debug:
        msg: "printing dictionary {{mydict}}"