- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name : 'nginx', state: 'latest'}
    - {name : 'mysql', state: 'absent'}