- name: variables
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: Please enter username
      private: false
    - name: PASSWORD
      prompt: Please enter password
      private: true
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Hi, Username is {{USERNAME}} and password is {{PASSWORD}}"